# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f40f0fcb22e6d2b1773a95abf1b777fe0aac0528e011feeb7230b627ba730776d19e3331d540899a0915e153430fcb901f17caea1e23ea3d43ae92561f802437

test:
  secret_key_base: 20730f7610a893f561e3ff7ac454202dc6e22e293b54a67b29088ec4e1bf79a7764bddd15fee6bc9942f189f7e2800ca8f750cf78e2624cb93a6ab225f07e889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
